/**
 * To use a custom icon font, add the ttf font file to the assets-folder and import it
 * in the App.js at 'Font.loadAsync'. Update the glyph map below to match your font
 * and check the font name in the function below.
 */

import {createIconSet} from "@expo/vector-icons";

const glyphMap = {
    "bus":                      "a",
    "tram":                     "b",
    "train":                    "b",
    "close":                    "c",
    "messages":                 "s",
    "menu":                     "I",
    "grid":                     "I",
    "more-horizontal":          "e",
    "more-vertical":            "d",
    "paperplane-outline":       "f",
    "partlysunny":              "f",
    "partlysunny-outline":      "f",
    "rainy":                    "f",
    "rainy-outline":            "f",
    "thunderstorm":             "f",
    "thunderstorm-outline":     "f",
    "sunny":                    "f",
    "sunny-outline":            "f",
    "print":                    "m",
    "hilfe":                    "r",
    "lock":                     "P",
    "lock-open":                "Q",
    "navigation":               "o",
    "profile":                  "n",
    "opal":                     "s",
    "mensa":                    "H",
    "location":                 "p",
    "inbox":                    "l",
    "imprint":                  "D",
    "pts":                      "a",
    "feedback":                 "E",
    "book":                     "B",
    "news":                     "J",
    "arrow-left":               "h",
    "arrow-down":               "i",
    "arrow-right":              "k",
    "arrow-up":                 "j",
    "download":                 "l",
    "back":                     "h",
    "forward":                  "k",
    "rss":                      "O",
    "map-search":               0x2e,
    "dashboard":                "G",
    "timetable":                "N",
    "search":                   "L",
    "settings":                 "F",
    "coffee":                   "R",
    "material-mail":            "S",
    "manage-accounts":          "F",
    "check":                    "t",
    "star":                     "u",
    "star-selected":            "v",
    "edit":                     "w",
    "time":                     "x",
    "open-external":            "y",
    "share":                    "y",
    "accessibility":            "A",
    "wifi":                     "K",
    "rocket":                   "T",
    "info":                     0x2139,
    "up":                       0xca,
    "down":                     0xcb,
    "left":                     0xcc,
    "right":                    0xcd,
    "expand-less":              0x84,
    "mensa-garlic":             0xe90e,
    "mensa-vegan":              0xe906,
    "mensa-chicken":            0xe910,
    "mensa-vegetarian":         0xe902,
    "mensa-pork":               0xe911,
    "mensa-beef":               0xe90c,
    "mensa-fish/seafood":       0xe90d,
    "mensa-alcohol":            0xe90f,
    "mensa-gluten-free":        0xe907,
    "mensa-lactose-free":       0xe903,
    "mensa-hot":                0xe909,
    "mensa-venison":            0xaa,
    "mensa-lamb":               0xab,
    "mensa-climate-dish":       0xa1,
    "mensa-bio":                0xa1,
    "mensa-insects":            0xa2,
};
export default createIconSet(glyphMap, 'openasist');
